### ISSUE TITLE
This video keeps stopping at 7:26 and there is no way to see the end.

### ISSUE THREAD

**Issue by jodonnell2** [AdobeDocs/journey-optimizer-learn.en#3]
Issue in ./help/create-journeys/introduction-to-building-a-journey.md

This video keeps stopping at 7:26 and there is no way to see the end.

**Comment by sanhaus** [comment]
I cannot reproduce the issue. I can watch the full video to the end:

https://experienceleague.adobe.com/docs/journey-optimizer-learn/tutorials/create-journeys/introduction-to-building-a-journey.html?lang=en

I am on Google Chrome. I have also refreshed the video. Please let me know if you are still seeing this issue.
