### ISSUE TITLE
Video out of date

### ISSUE THREAD

**Issue by dwright-adobe** [AdobeDocs/journey-optimizer-learn.en#6]
Issue in ./help/set-up-access/create-and-manage-sandboxes.md

This video is out of date and does not include changes to the location of the sandbox switcher and management of user permissions in the newer Permissions screen instead of Admin Console. Perhaps you can just use this more recent video since it applies to AJO?
https://experienceleague.adobe.com/en/docs/platform-learn/tutorials/admin/use-sandboxes

**Comment by sanhaus** [comment]
@dwright-adobe, I updated the page and embedded the AEP video as suggested.
